
module MEM312X48 (
    PD,
    CLK,
    MEA,
    WEA,
    ADRA,
    DA, 
    MEB,
    ADRB,
    QB
);

/* This is only a model for memory.
   Please replace this model with the one generated by
   the memory compiler you use. */

input PD;           // power down enable
input CLK;          // clock
input MEA;          // active low enable
input WEA;          // active low write enable
input [8:0] ADRA;   // write address
input [47:0] DA;    // data in
input MEB;          // active low enable
input [8:0] ADRB;   // read address
output [47:0] QB;   // data out

reg [47:0] QB;
reg [47:0] MEMORY [0:311];

always @(posedge CLK)
    if (!PD && MEB)
         QB <= MEMORY[ADRB];

always @(posedge CLK)
    if (!PD && MEA && WEA)
        MEMORY[ADRA] <= DA;

endmodule

